#Config generated on Fri Aug 3 19:10:36 2018
#MongoDB settings
MongoDB:
  host: "localhost"
  port: 27017
  user: "admin"
  password: "123456"
  collection: "communitytools"

#Swift Openstack settings (ignore it if you are not going to use it)
OpenstackSwift:
  host: "localhost"
  port: 12345
  user: "ComToolsUser"

#Generall settings
#Use the locally filesystem instead of OpenStack Swift?
useFileSystem: true
